export const practiceAreas = [
  { name: "Sex Crimes" },
  { name: "Theft" },
  { name: "Criminal Law" },
  { name: "Misdemeanors" },
  { name: "Traffic Tickets" },
  { name: "Felonies" },
  { name: "DUI/DWI" },
  { name: "Parole and Probation" },
  { name: "Drug Crimes" },
  { name: "Juvenile Law" },
  { name: "Homicide" },
  { name: "Traffic Violations" },
  { name: "Divorce" },
  { name: "Family Law" },
  { name: "Child Custody" },
  { name: "Adoptions" },
  { name: "Spousal Support" },
  { name: "Visitation Rights" },
  { name: "Paternity" },
  { name: "Premarital Agreements" },
  { name: "Child Support" },
  { name: "Head and Spinal Injuries" },
  { name: "Nursing Home Litigation" },
  { name: "Landlord and Tenant" },
  { name: "Automobile Accidents" },
  { name: "Personal Injury" },
  { name: "Trucking Accidents" },
  { name: "Slip and Fall" },
  { name: "Railroad Accidents" },
  { name: "Sexual Abuse" },
  { name: "Dog Bites" },
  { name: "Boating Accidents" },
  { name: "Wrongful Death" },
];
